"""
Unwind Visual Cortex - Pexels API Integration
Automated B-roll video sourcing from Pexels stock footage library

This module provides functions to search and download royalty-free videos
from Pexels based on shot list descriptions generated by the Visual Cortex.

API Documentation: https://www.pexels.com/api/documentation/
"""

import os
import time
import requests
from typing import List, Dict, Optional, Any
from datetime import datetime, timedelta


class PexelsAPIError(Exception):
    """Custom exception for Pexels API errors"""
    pass


class RateLimiter:
    """Rate limiter for Pexels API (200 requests/hour)"""
    
    def __init__(self, max_requests: int = 200, time_window: int = 3600):
        """
        Initialize rate limiter
        
        Args:
            max_requests: Maximum requests allowed in time window (default: 200)
            time_window: Time window in seconds (default: 3600 = 1 hour)
        """
        self.max_requests = max_requests
        self.time_window = time_window
        self.requests = []
    
    def wait_if_needed(self) -> None:
        """Wait if rate limit would be exceeded"""
        now = datetime.now()
        
        # Remove requests outside the time window
        cutoff = now - timedelta(seconds=self.time_window)
        self.requests = [req_time for req_time in self.requests if req_time > cutoff]
        
        # Check if we're at the limit
        if len(self.requests) >= self.max_requests:
            # Calculate how long to wait
            oldest_request = self.requests[0]
            wait_until = oldest_request + timedelta(seconds=self.time_window)
            wait_seconds = (wait_until - now).total_seconds()
            
            if wait_seconds > 0:
                print(f"⏳ Rate limit reached. Waiting {wait_seconds:.1f} seconds...")
                time.sleep(wait_seconds)
                # Clear old requests after waiting
                self.requests = []
        
        # Record this request
        self.requests.append(now)


class PexelsClient:
    """Client for interacting with Pexels API"""
    
    def __init__(self, api_key: Optional[str] = None):
        """
        Initialize Pexels client
        
        Args:
            api_key: Pexels API key (if None, reads from PEXELS_API_KEY env var)
        """
        self.api_key = api_key or os.getenv('PEXELS_API_KEY')
        if not self.api_key:
            raise ValueError(
                "Pexels API key not provided. Set PEXELS_API_KEY environment variable "
                "or pass api_key parameter."
            )
        
        self.base_url = "https://api.pexels.com/videos"
        self.headers = {
            "Authorization": self.api_key
        }
        self.rate_limiter = RateLimiter(max_requests=180, time_window=3600)  # Conservative limit
    
    def search_videos(
        self,
        query: str,
        orientation: str = "landscape",
        size: str = "medium",
        per_page: int = 15,
        page: int = 1
    ) -> Dict[str, Any]:
        """
        Search for videos on Pexels
        
        Args:
            query: Search query (e.g., "business meeting", "city skyline")
            orientation: Video orientation (landscape, portrait, square)
            size: Video size (large, medium, small)
            per_page: Results per page (max 80)
            page: Page number
        
        Returns:
            Dictionary containing search results with video metadata
        
        Raises:
            PexelsAPIError: If API request fails
        """
        # Rate limiting
        self.rate_limiter.wait_if_needed()
        
        # Validate parameters
        valid_orientations = ["landscape", "portrait", "square"]
        if orientation not in valid_orientations:
            raise ValueError(f"orientation must be one of {valid_orientations}")
        
        valid_sizes = ["large", "medium", "small"]
        if size not in valid_sizes:
            raise ValueError(f"size must be one of {valid_sizes}")
        
        if per_page > 80:
            per_page = 80
        
        # Build request
        url = f"{self.base_url}/search"
        params = {
            "query": query,
            "orientation": orientation,
            "size": size,
            "per_page": per_page,
            "page": page
        }
        
        try:
            response = requests.get(url, headers=self.headers, params=params, timeout=10)
            response.raise_for_status()
            return response.json()
        
        except requests.exceptions.HTTPError as e:
            if response.status_code == 429:
                raise PexelsAPIError("Rate limit exceeded. Please try again later.")
            elif response.status_code == 401:
                raise PexelsAPIError("Invalid API key. Check your PEXELS_API_KEY.")
            else:
                raise PexelsAPIError(f"HTTP error {response.status_code}: {str(e)}")
        
        except requests.exceptions.RequestException as e:
            raise PexelsAPIError(f"Request failed: {str(e)}")
    
    def get_video_by_id(self, video_id: int) -> Dict[str, Any]:
        """
        Get video details by ID
        
        Args:
            video_id: Pexels video ID
        
        Returns:
            Dictionary containing video metadata
        
        Raises:
            PexelsAPIError: If API request fails
        """
        self.rate_limiter.wait_if_needed()
        
        url = f"{self.base_url}/videos/{video_id}"
        
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            return response.json()
        
        except requests.exceptions.RequestException as e:
            raise PexelsAPIError(f"Failed to get video {video_id}: {str(e)}")
    
    def download_video(
        self,
        video_url: str,
        output_path: str,
        chunk_size: int = 8192
    ) -> str:
        """
        Download a video file from Pexels
        
        Args:
            video_url: Direct URL to video file
            output_path: Path where video should be saved
            chunk_size: Download chunk size in bytes
        
        Returns:
            Path to downloaded file
        
        Raises:
            PexelsAPIError: If download fails
        """
        try:
            # Create output directory if it doesn't exist
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            
            # Download with streaming
            response = requests.get(video_url, stream=True, timeout=30)
            response.raise_for_status()
            
            total_size = int(response.headers.get('content-length', 0))
            downloaded = 0
            
            with open(output_path, 'wb') as f:
                for chunk in response.iter_content(chunk_size=chunk_size):
                    if chunk:
                        f.write(chunk)
                        downloaded += len(chunk)
                        
                        # Progress indicator
                        if total_size > 0:
                            progress = (downloaded / total_size) * 100
                            print(f"\r⬇️  Downloading: {progress:.1f}%", end='', flush=True)
            
            print()  # New line after progress
            return output_path
        
        except requests.exceptions.RequestException as e:
            raise PexelsAPIError(f"Download failed: {str(e)}")
    
    def find_best_match(
        self,
        query: str,
        orientation: str = "landscape",
        min_duration: Optional[int] = None,
        max_duration: Optional[int] = None
    ) -> Optional[Dict[str, Any]]:
        """
        Find the best matching video for a query
        
        Args:
            query: Search query
            orientation: Video orientation
            min_duration: Minimum duration in seconds (optional)
            max_duration: Maximum duration in seconds (optional)
        
        Returns:
            Best matching video metadata or None if no match found
        """
        results = self.search_videos(query, orientation=orientation, per_page=15)
        
        if not results.get('videos'):
            return None
        
        videos = results['videos']
        
        # Filter by duration if specified
        if min_duration or max_duration:
            filtered = []
            for video in videos:
                duration = video.get('duration', 0)
                if min_duration and duration < min_duration:
                    continue
                if max_duration and duration > max_duration:
                    continue
                filtered.append(video)
            videos = filtered
        
        # Return highest quality video (first result is usually best match)
        return videos[0] if videos else None
    
    def get_video_file_url(
        self,
        video_metadata: Dict[str, Any],
        quality: str = "hd"
    ) -> Optional[str]:
        """
        Extract video file URL from metadata
        
        Args:
            video_metadata: Video metadata from search results
            quality: Preferred quality (hd, sd, or specific resolution like "1920x1080")
        
        Returns:
            Direct URL to video file or None if not found
        """
        video_files = video_metadata.get('video_files', [])
        
        if not video_files:
            return None
        
        # Try to find exact quality match
        for file in video_files:
            if quality == "hd" and file.get('quality') == 'hd':
                return file.get('link')
            elif quality == "sd" and file.get('quality') == 'sd':
                return file.get('link')
            elif quality in [file.get('width'), f"{file.get('width')}x{file.get('height')}"]:
                return file.get('link')
        
        # Fallback to highest quality available
        hd_files = [f for f in video_files if f.get('quality') == 'hd']
        if hd_files:
            return hd_files[0].get('link')
        
        # Last resort: return first available
        return video_files[0].get('link')


def search_and_download_broll(
    shot_description: str,
    output_dir: str = "/home/ubuntu/unwind_visual_cortex/broll",
    orientation: str = "landscape",
    quality: str = "hd",
    api_key: Optional[str] = None
) -> Optional[str]:
    """
    Convenience function to search for and download B-roll footage
    
    Args:
        shot_description: Description of the shot needed (e.g., "business meeting")
        output_dir: Directory to save downloaded videos
        orientation: Video orientation
        quality: Video quality preference
        api_key: Pexels API key (optional, reads from env if not provided)
    
    Returns:
        Path to downloaded video file or None if not found
    
    Example:
        >>> video_path = search_and_download_broll("city skyline at sunset")
        >>> print(f"Downloaded: {video_path}")
    """
    try:
        client = PexelsClient(api_key=api_key)
        
        print(f"🔍 Searching for: {shot_description}")
        video = client.find_best_match(shot_description, orientation=orientation)
        
        if not video:
            print(f"❌ No videos found for: {shot_description}")
            return None
        
        print(f"✅ Found: {video.get('id')} - {video.get('width')}x{video.get('height')}")
        
        # Get download URL
        video_url = client.get_video_file_url(video, quality=quality)
        if not video_url:
            print(f"❌ No download URL available")
            return None
        
        # Generate filename
        safe_description = "".join(c for c in shot_description if c.isalnum() or c in (' ', '-', '_')).strip()
        safe_description = safe_description.replace(' ', '_')[:50]
        filename = f"{safe_description}_{video['id']}.mp4"
        output_path = os.path.join(output_dir, filename)
        
        # Download
        print(f"⬇️  Downloading to: {output_path}")
        client.download_video(video_url, output_path)
        print(f"✅ Download complete!")
        
        return output_path
    
    except PexelsAPIError as e:
        print(f"❌ Pexels API Error: {str(e)}")
        return None
    except Exception as e:
        print(f"❌ Unexpected error: {str(e)}")
        return None


# Example usage
if __name__ == "__main__":
    # Test the integration
    print("Testing Pexels API Integration...")
    print("=" * 60)
    
    # Check for API key
    if not os.getenv('PEXELS_API_KEY'):
        print("⚠️  PEXELS_API_KEY environment variable not set")
        print("Set it with: export PEXELS_API_KEY='your_api_key_here'")
        print("\nGet your free API key at: https://www.pexels.com/api/")
    else:
        # Test search
        client = PexelsClient()
        results = client.search_videos("business meeting", per_page=3)
        print(f"✅ Search test: Found {results.get('total_results', 0)} videos")
        
        if results.get('videos'):
            video = results['videos'][0]
            print(f"   First result: {video.get('width')}x{video.get('height')}, {video.get('duration')}s")
